source 'http://rubygems.org'
source 'http://gems.github.com'

gem 'rails', '3.0.0.beta2'
gem 'authlogic', :git => 'git://github.com/binarylogic/authlogic.git'
gem 'capistrano', '2.5.18'
gem 'capistrano-ext', '1.2.1'
gem 'config_reader', '0.0.7'
gem 'friendly_id', '3.0.1'
gem 'formtastic', :git => 'git://github.com/justinfrench/formtastic.git'
gem 'haml', '>= 3.0.0.beta.1'
gem 'hoe', '2.5.0'
gem 'mongrel'
gem 'mysql'
gem 'seed-fu', '1.2.3'
gem 'test-unit', '1.2.3'
gem 'will_paginate', :git => 'git://github.com/mislav/will_paginate.git', :branch => 'rails3'

group :test do
  gem 'capybara'
  gem 'cucumber'
  gem 'cucumber-rails'
  gem 'database_cleaner'
  gem 'faker'
  gem 'launchy'
  gem 'machinist'
  gem 'pickle'
  gem 'rcov'
  gem 'rspec-rails', '>= 2.0.0.beta.1'
end
